// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrmuxhbnijacklratmom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlybXV4aGJuaWphY2tscmF0bW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzM0MTAsImV4cCI6MjA1OTk0OTQxMH0.mYTssVk-_9NYurEyYoeibCjF6mHddawzh56rmVrHpKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);